# Generated by Django 5.2.14 on 2026-05-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='services.service'),
        ),
    ]
